nomeCompleto = str(input("Digite seu nome completo: ")).strip()
nomeDividido = nomeCompleto.split()
print("Muito prazer em te conhecer!")
print(f"Seu primeiro nome é {nomeDividido[0]}")
print(f"Seu último nome é {nomeDividido[-1]}")
